name: C# CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore "Cyber Security Chatbot.sln"

    - name: Build project
      run: msbuild "Cyber Security Chatbot.sln" /p:Configuration=Release

    - name: Code Formatting Check (using dotnet format)
      run: dotnet format --verify-no-changes "Cyber Security Chatbot.sln"
